# This GitHub Actions workflow runs on every code change and configures the
# React app in the AWS Amplify Console using Node.js 16.
#
# First, the GitHub Action deploys the 'stack.yaml' AWS CloudFormation stack
# to your AWS Account. This stack configures the React app in the AWS Amplify Console.
#
# Then, you need to trigger a first build in the AWS Amplify Console to
# fully configure it.

name: Deploy

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  # Deploy the React app to AWS Amplify Console.
  amplify:
    name: Deploy to Amplify Console
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Configure environment name
      id: env-name
      env:
        REPO: ${{ github.repository }}
      run: |
        ENVIRONMENT=`echo $REPO | tr "/" "-"`
        echo "Environment name: $ENVIRONMENT"
        echo "::set-output name=environment::$ENVIRONMENT"

    - name: Deploy to Amplify Console with CloudFormation
      id: amplify-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ steps.env-name.outputs.environment }}
        template: stack.yaml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          Name=${{ steps.env-name.outputs.environment }},
          Repository=https://github.com/${{ github.repository }},
          OauthToken=${{ secrets.AMPLIFY_TOKEN }},
          Domain=${{ secrets.AMPLIFY_DOMAIN }}

    # When a domain is configured to the stack,
    # it gets configured in the environment and printed to the console.
    - name: Print default domain
      env:
        DefaultDomain: ${{ steps.amplify-stack.outputs.DefaultDomain }}
      run: |
        echo "Default Domain: $DefaultDomain"
